url: bluesmile82.github.io
baseurl:

# Site settings
title: Alvaro Leal
email: info@alvaro-leal.com
description: " Hi! I’m a Full-stack Ruby on Rails developer. I live in Brussels, Belgium. I am open to new projects and job opportunities.  I Hope you enjoy my portfolio.  Have a nice day!."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 74B2AD
  secondary: 236863
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/midnightstomp
  - title: linkedin
    url: https://be.linkedin.com/in/alvaroleal
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/bluesmile82

# Postal address (add as many lines as necessary)
address:
  # - line: 3481 Melrose Place
  - line: Brussels, Belgium 1050

# Build settings
markdown: kramdown
permalink: pretty
auto: true

ftp_host: 'ftp.alvaro-leal.com'
ftp_dir: '/al/'
ftp_passive: false
